### ISSUE TITLE
Citas offline

### ISSUE THREAD

**Issue by lgaticaq** [raulghm/vue-lavin-quotes#5]
La idea es que en la primera carga queden almacenadas en el store el array de citas, y que desde allí obtenga una random.
Luego las próximas veces obtenga una nueva desde el store.
Cada vez que obtenga una nueva quitarlas del store (pop).
Cuando ya no queden obtener un nuevo listado desde la api.

**Comment by raulghm** [comment]
Actualizado en el ultimo update ;)
